# Generated by Django 4.2 on 2023-04-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'date'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
