# Generated by Django 4.2 on 2023-04-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Préstamo')),
                ('devolution_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('returned', models.BooleanField(default=False, verbose_name='Devuelto')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_related', to='book.book', verbose_name='Titulo del Libro')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader', verbose_name='Lector')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
