# Generated by Django 4.2 on 2023-04-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_loan_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='edad',
            new_name='age',
        ),
    ]
