# Generated by Django 4.2 on 2023-04-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='edad',
            new_name='age',
        ),
    ]
